import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    padding: 20,
    backgroundColor: '#f7f7f7',
  },
  title: {
    textAlign: 'center',
    fontSize: 60,
    color: '#FFFF',
    marginBottom: 20,
    marginTop: 50,
    fontWeight: 'bold',
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowOpacity: 0.5,
    textShadowRadius: 8,
  },
  subTitle: {
    textAlign: 'left',
    fontSize: 22,
    fontWeight: '600',
    color: '#FF6347',
    marginBottom: 15,
    textShadowColor: '#000',
    textShadowOffset: { width: 0, height: 1 },
    textShadowOpacity: 0.75,
    textShadowRadius: 3.5,
  },
  inputContainer: {
    width: '100%',
    paddingTop: 20,
    alignItems: 'stretch',
    marginBottom: 15,
  },
  input: {
    height: 45,
    borderColor: '#ddd',
    borderWidth: 1,
    marginBottom: 12,
    paddingLeft: 10,
    borderRadius: 8,
    backgroundColor: '#fff',
    fontSize: 18,
    color: '#333',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  inputError: {
    borderColor: '#FF4500',
    borderWidth: 1.5,
    marginBottom: 10,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    paddingHorizontal: 25,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  label: {
    fontSize: 18,
    marginVertical: 12,
    color: '#FFF',
  },
  genderButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  genderButton: {
    backgroundColor: '#FF4500',
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 30,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  selectedGenderButton: {
    backgroundColor: '#FF6347',
  },
  genderButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',  // Keskittää napit vaakasuunnassa
    alignItems: 'stretch',      // Keskittää napit pystysuunnassa
    marginTop: 25,
    paddingHorizontal: 20,
  },  
  wideButton: {
    backgroundColor: '#FF4500',
    borderRadius: 25,
    paddingVertical: 15,
    paddingHorizontal: 35,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  saveButton: {
    backgroundColor: '#FF6347',
    borderRadius: 50,
    paddingVertical: 14,
    paddingHorizontal: 20,
    width: 250,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '10%',
    marginLeft: 50,
    marginBottom: 70,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 15,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  addButton: {
    backgroundColor: '#FF4500',
    borderRadius: 25,
    paddingHorizontal: 25,
    paddingVertical: 12,
    marginLeft: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  addButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  exerciseItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 25,
    backgroundColor: '#fff',
    borderRadius: 30,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1.0,
    shadowRadius: 2,
    elevation: 5,
    width: '100%',
  },
  exerciseText: {
    fontSize: 20,
    color: '#333',
    fontWeight: '600',
    flex: 1,
    paddingVertical: 5,
    textAlign: 'center',
  },
  categoryTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#FF6347',
    paddingVertical: 10,
    paddingHorizontal: 25,
    marginTop: 20,
    marginBottom: 10,
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowOpacity: 0.5,
    textShadowRadius: 5,
    textAlign: 'left',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '90%',
    backgroundColor: '#fff',
    padding: 35,
    borderRadius: 20,
    alignItems: 'center',
    elevation: 12,
  },
  modalTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#FF4500',
  },
  modalLabel: {
    fontSize: 20,
    fontWeight: '600',
    marginVertical: 20,
    color: '#333',
  },
  calendarContainer: {
    flex: 1,
    padding: 20,
  },
  listItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    padding: 20,
    marginBottom: 12,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sportText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },

  removeButton: {
    flexDirection: 'row',
    backgroundColor: '#FF4C4C',
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,  // Vähentää välimatkaa napin ja seuraavan napin välillä
    elevation: 15,
  },
  completedButton: {
    backgroundColor: '#28a745', // Green color
    borderRadius: 50, // Same border radius as the remove button
    paddingVertical: 6, // Same padding as the remove button
    paddingHorizontal: 14, // Same horizontal padding as the remove button
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 15, // Same elevation as the remove button
  },
  noDataText: {
    fontSize: 18,
    color: '#888',
    textAlign: 'center',
    marginTop: 20,
  },
  goalButtonContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    marginTop: 20,
  },
  goalButton: {
    backgroundColor: '#FF4500',
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 20,
    margin: 8,
    alignItems: 'center',
    justifyContent: 'center',
    width: '45%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  selectedGoalButton: {
    backgroundColor: '#FF6347',
    borderWidth: 2,
    borderColor: '#FFF',
  },
  goalButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  selectedGoalButtonText: {
    fontWeight: 'bold',
    textDecorationLine: 'underline',
  },
  profileText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFF',
    textAlign: 'center',
    marginVertical: 8,
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
    letterSpacing: 1.2,
    backgroundColor: 'rgb(255, 68, 0)',
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 15,
    overflow: 'hidden',
  },
  profileDetail: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFD700',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  profileContainer: {
    padding: 20,
    backgroundColor: 'rgba(104, 103, 103, 0.42)', 
    borderRadius: 10,
    marginTop: 20,
  },
  profileText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: 'rgb(0, 0, 0)',
    marginBottom: 10,
    textAlign: 'left',
  },
  profileDetail: {
    fontSize: 22,
    fontWeight: 'bold',
    color: 'rgb(255, 255, 255)',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 10,
  },
  editButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    paddingVertical: 8,
    paddingHorizontal: 25,
    marginVertical: 10,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  editButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  saveButton: {
    backgroundColor: 'rgba(78, 78, 78, 0.27)',
    paddingVertical: 14,
    paddingHorizontal: 20,
    width: 250,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '10%',
    marginLeft: 50,
    marginBottom: 70,
    borderRadius: 50,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 15,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  input: {
    height: 45,
    borderColor: '#ddd',
    borderWidth: 1,
    marginBottom: 12,
    paddingLeft: 10,
    borderRadius: 8,
    backgroundColor: 'rgb(104, 103, 103)',
    fontSize: 18,
    color: '#333',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  inputError: {
    borderColor: '#FF4500',
    borderWidth: 1.5,
    marginBottom: 10,
  },
  // New component style
  newComponent: {
    backgroundColor: '#FFD700',
    padding: 15,
    borderRadius: 10,
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  newComponentText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
});

export default styles;
